sudo: required
services:
  - docker

before_install:
  - docker build -t tranhieuqn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tranhieuqn/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-728113759221"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY